export const FONT_URL = "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Cinzel:wght@400;600;700&family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;500;600;700&display=swap";

// ── Themes ────────────────────────────────────────────────────────────────────
export const THEMES = {
  nature:    { id:"nature",    name:"Nature",      emoji:"🌿", tagline:"Grow your savings like a garden",      bg:"#f0f7ec", card:"#ffffff", grad:"linear-gradient(160deg,#dff0d8,#f0f7ec 60%)", c:{p:"#4a7c59",pl:"#e2f0db",acc:"#f9c74f",danger:"#d95f0e",text:"#2d4a3e",muted:"#7a9e82",border:"#c5e0b8",nav:"#3a6347",navT:"#ffffff",overlay:"rgba(42,74,56,0.65)"}, font:'"Nunito",sans-serif',       w:{home:"My Grove",    txn:"Gatherings",   budget:"Garden Limit", inc:"Harvest", over:"Over your garden limit 🌱"},  npc:"🦔",npcName:"Hedgie",  chat:["Oh! A rustling in the leaves... 🍃","A new friend has arrived at the grove!","The forest remembers every acorn you spend.","Shall I help you track yours?"],          avatars:["🐸","🦔","🐰","🦋","🐿️","🦉"] },
  adventure: { id:"adventure", name:"Adventure",   emoji:"⚔️", tagline:"Track your gold, conquer your quests", bg:"#fdf6e3", card:"#fffdf5", grad:"linear-gradient(160deg,#fdebd0,#fdf6e3 60%)", c:{p:"#8b5e3c",pl:"#fdebd0",acc:"#d4a017",danger:"#c0392b",text:"#3d1c02",muted:"#a07040",border:"#e8d5b0",nav:"#5c3418",navT:"#ffeeba",overlay:"rgba(60,28,2,0.65)"},   font:'"Cinzel",Georgia,serif',    w:{home:"Map Room",    txn:"Journey Log",  budget:"War Chest",    inc:"Loot",    over:"War chest depleted! ⚔️"},          npc:"🧙",npcName:"Merlin",  chat:["Halt, brave traveler! ⚔️","Many heroes have lost their gold to careless spending.","A wise adventurer tracks every coin.","Are you ready to begin?"],               avatars:["🦊","🐺","🦁","🐉","🧙","🏹"] },
  princess:  { id:"princess",  name:"Princess",    emoji:"👸", tagline:"Rule your royal treasury with grace",  bg:"#fff5f9", card:"#ffffff", grad:"linear-gradient(160deg,#fce4f0,#fff5f9 60%)", c:{p:"#b5478a",pl:"#fce4f0",acc:"#ffd700",danger:"#e74c6d",text:"#5c1f3b",muted:"#9c6080",border:"#f0c0d8",nav:"#8f2a68",navT:"#fff0f8",overlay:"rgba(92,31,59,0.65)"},  font:'"Playfair Display",Georgia,serif', w:{home:"Royal Court",  txn:"Royal Ledger", budget:"Royal Decree", inc:"Tribute", over:"Exceeding royal decree! 👑"},        npc:"🧚",npcName:"Fae",     chat:["Oh my stars! A new arrival! ✨","Welcome to your royal treasury, darling! 👑","Every gem spent and coin saved matters.","Shall we begin your reign?"],            avatars:["👸","🧚","🦄","🌸","🎀","💎"] },
  finance:   { id:"finance",   name:"Finance Pro", emoji:"📊", tagline:"Clean data. Clear decisions.",         bg:"#f8fafc", card:"#ffffff", grad:"#f8fafc",                                      c:{p:"#2563eb",pl:"#dbeafe",acc:"#10b981",danger:"#ef4444",text:"#0f172a",muted:"#64748b",border:"#e2e8f0",nav:"#1e40af",navT:"#ffffff",overlay:"rgba(15,23,42,0.65)"},   font:'"Inter",system-ui,sans-serif',  w:{home:"Overview",    txn:"Transactions", budget:"Allocation",   inc:"Revenue", over:"Budget exceeded ⚠️"},            npc:"🤖",npcName:"Fin",     chat:["Welcome to your finance dashboard.","Your data stays 100% on this device.","Track spending, set budgets, plan ahead.","Let's get started."],                          avatars:["🐻","🦅","🐬","🦉","🐆","🤖"] },
};
export const THEMES_TR = {
  nature: {
    en: { name:"Nature", tagline:"Grow your savings like a garden",
      chat:["Oh! A rustling in the leaves... 🍃","A new friend has arrived at the grove!","The forest remembers every acorn you spend.","Shall I help you track yours?"] },
    es: { name:"Naturaleza", tagline:"Haz crecer tus ahorros como un jardín",
      chat:["¡Oh! Un susurro entre las hojas... 🍃","¡Un nuevo amigo ha llegado al jardín!","El bosque recuerda cada bellota que gastas.","¿Te ayudo a llevar la cuenta?"] }
  },
  adventure: {
    en: { name:"Adventure", tagline:"Track your gold, conquer your quests",
      chat:["Halt, brave traveler! ⚔️","Many heroes have lost their gold to careless spending.","A wise adventurer tracks every coin.","Are you ready to begin?"] },
    es: { name:"Aventura", tagline:"Controla tu oro, conquista tus misiones",
      chat:["¡Alto, valiente viajero! ⚔️","Muchos héroes perdieron su oro por gastar sin control.","Un aventurero sabio lleva cuenta de cada moneda.","¿Estás listo para empezar?"] }
  },
  princess: {
    en: { name:"Princess", tagline:"Rule your royal treasury with grace",
      chat:["Oh my stars! A new arrival! ✨","Welcome to your royal treasury, darling! 👑","Every gem spent and coin saved matters.","Shall we begin your reign?"] },
    es: { name:"Princesa", tagline:"Gobierna tu tesoro real con elegancia",
      chat:["¡Cielos! ¡Una nueva llegada! ✨","Bienvenida a tu tesoro real, querida! 👑","Cada gema gastada y moneda ahorrada importa.","¿Comenzamos tu reinado?"] }
  },
  finance: {
    en: { name:"Finance Pro", tagline:"Clean data. Clear decisions.",
      chat:["Welcome to your finance dashboard.","Your data stays 100% on this device.","Track spending, set budgets, plan ahead.","Let's get started."] },
    es: { name:"Finanzas Pro", tagline:"Datos claros. Decisiones claras.",
      chat:["Bienvenida a tu panel financiero.","Tus datos se quedan 100% en este dispositivo.","Controla gastos, fija presupuestos, planifica.","Empecemos."] }
  }
};
export const GOALS = [{id:"save",e:"💰",label:"Save for something",sub:"I have a goal in mind"},{id:"cut",e:"✂️",label:"Cut my spending",sub:"I want to spend less"},{id:"know",e:"🔍",label:"Understand my money",sub:"See where it all goes"},{id:"chill",e:"✨",label:"Just exploring",sub:"Curious about finances"}];
export const GOALS_TR = {
  en:{save:{label:"Save for something",sub:"I have a goal in mind"},cut:{label:"Cut my spending",sub:"I want to spend less"},know:{label:"Understand my money",sub:"See where it all goes"},chill:{label:"Just exploring",sub:"Curious about finances"}},
  es:{save:{label:"Ahorrar para algo",sub:"Tengo una meta en mente"},cut:{label:"Gastar menos",sub:"Quiero reducir mis gastos"},know:{label:"Entender mis finanzas",sub:"Ver en qué se gasta todo"},chill:{label:"Solo explorando",sub:"Curiosidad financiera"}},
};

// ── Translations ──────────────────────────────────────────────────────────────
export const T = {
  en:{
    home:"Overview",budgets:"Budgets",reminders:"Reminders",autoPay:"Auto Pay",data:"Data",
    income:"Income",expenses:"Expenses",net:"Net",biggestExpense:"Biggest expense",
    allTime:"All Time",thisWeek:"This Week",lastWeek:"Last Week",thisMonth:"This Month",lastMonth:"Last Month",
    custom:"Custom",compare:"Compare",
    noData:"No data yet",noDataSub:"Go to the Data tab and upload your bank export.",
    insights:"Insights",topSpend:"Top spend",mostVisited:"Most visited",avgDay:"Avg/day",
    upcomingCharges:"Upcoming charges",noPayments:"No auto payments set",
    inDays:"in",days:"days",day:"day",
    export:"Export Excel",exportBtn:"Download .xlsx",
    journal:"Transactions",noTxns:"No transactions this month",
    spent:"spent",transactions:"transactions",expenses2:"expenses",
    editCat:"Click to edit category",
    addComment:"Add a note…",saveComment:"Save",cancel:"Cancel",
    addReminder:"Reminder",markReimbursed:"Mark reimbursed",
    reimbursedLabel:"Reimbursed",removeReimb:"Remove",
    reason:"Reason (e.g. Maria paid me back half)",
    linkTo:"Link to transaction",searchTxn:"Search for the matching transaction…",
    budgetTitle:"Budget Limits",budgetSub:"Monthly limits per category. Groups let you bundle categories.",
    noLimit:"No limit set",setLimit:"Set limit",edit:"Edit",
    exceeded:"Budget exceeded ⚠️",month:"Month",week:"Week",
    individualLimits:"Individual Limits",weeklyNote:"monthly ÷ 4",
    remindersTitle:"Reminders",remindersSub:"To-dos, one-offs, and recurring nudges",
    newReminder:"+ New reminder",placeholder:"e.g. Take out €200 cash",
    once:"once",weekly:"weekly",monthly:"monthly",addReminderBtn:"Add reminder",
    autoPayTitle:"Auto Payments",autoPaySub:"Recurring charges — know what's coming",
    monthlyCommitments:"Monthly commitments",charges:"charges",
    everyMonth:"every month",everyYear:"every year",
    remove:"remove",addPayment:"Add payment",
    name:"Name (e.g. Spotify)",amount:"€ Amount",dayOfMonth:"Day",
    dataTitle:"Your Data",dataSub:"Upload your bank export",supportedBanks:"Supported banks",
    dropHere:"Drop your bank export here",dropIt:"Drop it!",chooseFile:"Choose file",
    privacyTitle:"100% Private",privacyBody:"Everything parsed in your browser. Nothing sent anywhere. Ever.",
    saveSession:"Save your session",saveSessionBody:"Download your data with all categories and notes. Next time re-upload this file — your classifications will be remembered.",
    dataLoaded:"Data loaded",viewLedger:"View full",
    memoryActive:"Merchant memory active",memoryBody:"merchants remembered — next upload auto-classifies these",
    clearMemory:"Clear",viewMemory:"View",hideMemory:"Hide",rememberedMerchants:"Remembered merchants",
    helpBanks:"Help us support more banks",helpBanksSub:"Is your bank not working? Share an anonymised export sample.",
    warning:"⚠️ Before uploading: open your export in Excel, delete ALL rows with real transactions, and keep ONLY the first header row (column names). Never share real financial data.",
    shareBtn:"📋 Share a sample export →",
    feedbackLink:"💬 Found a bug or have a suggestion? → Open an issue on GitHub",
    subsDetected:"Subscriptions detected",subsSub:"Tick yours & set frequency — some are billed yearly, not monthly.",
    billing:"Billing:",billingMonthly:"🗓 Monthly",billingYearly:"📅 Yearly",
    perMonth:"per month",perYear:"per year",renewsDay:"renews day",detected:"Detected:",
    confirmAutoPay:"Confirm & add to Auto Pay ✓",
    classifyTitle:"Classify merchants",classifyInstruction:"Click a merchant and pick its category",
    classifyActive:"Now tap a category below to assign",
    classifyDrop:"Drop on a category ↓",createCategory:"+ Create new category (e.g. Pets)",
    add:"Add",categories:"Categories",removeUnneeded:"(✕ to remove unneeded)",assigned:"Assigned ✓",
    doneBtn:"Done — save all ✓",leftToClassify:"merchants left to classify",
    budgetWizardTitle:"Set your budgets",budgetWizardSub:"What's your approximate monthly income? We'll suggest smart limits.",
    skipManual:"Skip — set manually →",suggestLimits:"Suggest my limits →",
    adjustTitle:"✏️ Adjust monthly limits",adjustSub:"Based on your income. Change anything that doesn't fit.",
    back:"← Back",saveBudgets:"Save budgets 🎯",
    tutorialTitle:"Quick guide — how Moneda works",
    step1Title:"Download your bank export 🏦",step1Sub:"Log into your bank's website, go to transaction history and download as Excel (.xlsx or .csv). Works with Santander, BBVA, CaixaBank, ING, Bankinter, Sabadell and more.",
    step2Title:"Upload it to Moneda 📂",step2Sub:"Go to the Data tab and drop your file. Moneda reads it instantly — nothing is sent anywhere, everything stays on your device.",
    step3Title:"Classify & customise 🗂️",step3Sub:"We auto-categorise most transactions. You can correct any, set monthly budgets, add reminders and track subscriptions.",
    step4Title:"💾 Save your session before you leave",step4Sub:"Any categories, budgets and reminders you create exist only in this tab. Before closing, go to Data and tap Download .xlsx — next time upload that file to restore everything.",
    gotIt:"Got it — let's go! 🚀",
    spendingTitle:"Spending by category",totalSpentIn:"Total spent in",byMerchant:"By merchant",
    insightsLabel:"Insights",
    categoryGroups:"Category Groups",createGroup:"+ Create category group (e.g. Food = Groceries + Restaurants)",
    newGroup:"New group",groupName:"Group name (e.g. Food)",selectCategories:"Select categories:",
    createGroupBtn:"Create group",removeGroup:"remove group",
    pickLang:"Choose your language",
    welcomeTitle:"Welcome to Moneda",pickWorld:"Pick your world",enterWorld:"Enter this world →",
    quickStart:"⚡ Quick start — just pick a name",selected:"✓ Selected",
    whatsYourName:"What's your name?",nameForDashboard:"Just for your dashboard — no account needed.",
    namePlaceholder:"Your name…",letsGo:"Let's go! 🚀",continueBtn:"Continue →",
    pickCompanion:"Pick your companion",whoJoins:"Who's joining you on this journey?",
    thisIsYou:"This is you!",perfect:"Perfect! →",
    whyHere:"Why are you here?",noWrongAnswers:"No wrong answers",
    startJourney:"Start my journey 🚀",pickOption:"Pick an option above",
    customise:"Customise",customDone:"Done",
    dragReorder:"Drag widgets to reorder, or hide ones you don't need:",
    visible:"Visible",hidden:"Hidden",
    wSummary:"📊 Summary cards",wInsights:"💡 Insights",wBudget:"🎯 Budget",
    wPayments:"💳 Upcoming charges",wSpending:"📊 Spending by category",
    wJournal:"📄 Journal",wIncome:"💰 Income transactions",
    wSubscriptions:"📦 Subscriptions & Recurring",
  },
  es:{
    home:"Inicio",budgets:"Presupuestos",reminders:"Recordatorios",autoPay:"Pagos fijos",data:"Datos",
    income:"Ingresos",expenses:"Gastos",net:"Balance",biggestExpense:"Mayor gasto",
    allTime:"Todo el tiempo",thisWeek:"Esta semana",lastWeek:"Semana pasada",thisMonth:"Este mes",lastMonth:"Mes pasado",
    custom:"Personalizado",compare:"Comparar",
    noData:"Sin datos aún",noDataSub:"Ve a la pestaña Datos y sube el extracto de tu banco.",
    insights:"Resumen",topSpend:"Mayor gasto",mostVisited:"Sitio más frecuente",avgDay:"Media/día",
    upcomingCharges:"Próximos cobros",noPayments:"No hay pagos automáticos",
    inDays:"en",days:"días",day:"día",
    export:"Exportar Excel",exportBtn:"Descargar .xlsx",
    journal:"Movimientos",noTxns:"No hay movimientos este mes",
    spent:"gastado",transactions:"movimientos",expenses2:"gastos",
    editCat:"Clic para editar categoría",
    addComment:"Añade una nota…",saveComment:"Guardar",cancel:"Cancelar",
    addReminder:"Recordatorio",markReimbursed:"Marcar como reembolsado",
    reimbursedLabel:"Reembolsado",removeReimb:"Eliminar",
    reason:"Motivo (ej: María me devolvió la mitad)",
    linkTo:"Vincular con movimiento",searchTxn:"Busca el movimiento correspondiente…",
    budgetTitle:"Límites de presupuesto",budgetSub:"Límites mensuales por categoría. Los grupos permiten agrupar categorías.",
    noLimit:"Sin límite",setLimit:"Poner límite",edit:"Editar",
    exceeded:"Presupuesto superado ⚠️",month:"Mes",week:"Semana",
    individualLimits:"Límites individuales",weeklyNote:"mensual ÷ 4",
    remindersTitle:"Recordatorios",remindersSub:"Tareas, avisos puntuales y recordatorios recurrentes",
    newReminder:"+ Nuevo recordatorio",placeholder:"ej: Sacar €200 en efectivo",
    once:"una vez",weekly:"semanal",monthly:"mensual",addReminderBtn:"Añadir recordatorio",
    autoPayTitle:"Pagos automáticos",autoPaySub:"Cargos recurrentes — sabe siempre lo que viene",
    monthlyCommitments:"Compromisos mensuales",charges:"cargos",
    everyMonth:"cada mes",everyYear:"cada año",
    remove:"eliminar",addPayment:"Añadir pago",
    name:"Nombre (ej: Spotify)",amount:"€ Importe",dayOfMonth:"Día",
    dataTitle:"Tus datos",dataSub:"Sube el extracto de tu banco",supportedBanks:"Bancos compatibles",
    dropHere:"Arrastra aquí el extracto de tu banco",dropIt:"¡Suéltalo!",chooseFile:"Elegir archivo",
    privacyTitle:"100% Privado",privacyBody:"Todo se procesa en tu navegador. Nada se envía a ningún servidor. Nunca.",
    saveSession:"Guarda tu sesión",saveSessionBody:"Descarga tus datos con todas las categorías y notas. La próxima vez sube este archivo y Moneda lo recuperará todo.",
    dataLoaded:"Datos cargados",viewLedger:"Ver todos los",
    memoryActive:"Memoria de comercios activa",memoryBody:"comercios guardados — la próxima subida los clasifica automáticamente",
    clearMemory:"Limpiar",viewMemory:"Ver",hideMemory:"Ocultar",rememberedMerchants:"Comercios recordados",
    helpBanks:"Ayúdanos a añadir más bancos",helpBanksSub:"¿Tu banco no funciona? Comparte una muestra anonimizada.",
    warning:"⚠️ Antes de subir: abre tu extracto en Excel, borra TODAS las filas con movimientos reales y deja SOLO la primera fila con los nombres de las columnas. Nunca compartas datos financieros reales.",
    shareBtn:"📋 Compartir muestra →",
    feedbackLink:"💬 ¿Encontraste un error o tienes una sugerencia? → Abrir issue en GitHub",
    subsDetected:"Suscripciones detectadas",subsSub:"Marca las tuyas y elige la frecuencia — algunas se cobran anualmente.",
    billing:"Facturación:",billingMonthly:"🗓 Mensual",billingYearly:"📅 Anual",
    perMonth:"al mes",perYear:"al año",renewsDay:"se renueva el día",detected:"Detectado:",
    confirmAutoPay:"Confirmar y añadir a Pagos fijos ✓",
    classifyTitle:"Clasificar comercios",classifyInstruction:"Haz click en un gasto y elige su categoría",
    classifyActive:"Ahora elige una categoría para",
    classifyDrop:"Suelta en una categoría ↓",createCategory:"+ Crear nueva categoría (ej: Mascotas)",
    add:"Añadir",categories:"Categorías",removeUnneeded:"(✕ para eliminar las que no necesitas)",assigned:"Asignados ✓",
    doneBtn:"Listo — guardar todo ✓",leftToClassify:"comercios sin clasificar",
    budgetWizardTitle:"Configura tus presupuestos",budgetWizardSub:"¿Cuáles son tus ingresos mensuales aproximados? Te sugeriremos límites.",
    skipManual:"Saltar — lo hago manualmente →",suggestLimits:"Sugerir límites →",
    adjustTitle:"✏️ Ajusta los límites mensuales",adjustSub:"Basados en tus ingresos. Cambia lo que no se ajuste a ti.",
    back:"← Atrás",saveBudgets:"Guardar presupuestos 🎯",
    tutorialTitle:"Guía rápida — cómo funciona Moneda",
    step1Title:"Descarga el extracto de tu banco 🏦",step1Sub:"Entra en la web o app de tu banco, ve al historial de movimientos y descárgalo como Excel (.xlsx o .csv). Compatible con Santander, BBVA, CaixaBank, ING, Bankinter, Sabadell y más.",
    step2Title:"Súbelo a Moneda 📂",step2Sub:"Ve a la pestaña Datos y arrastra tu archivo. Moneda lo lee al instante — nada se envía a ningún servidor, todo queda en tu dispositivo.",
    step3Title:"Clasifica y personaliza 🗂️",step3Sub:"Categorizamos la mayoría de movimientos automáticamente. Puedes corregir cualquiera, poner límites de presupuesto, añadir recordatorios y controlar suscripciones.",
    step4Title:"💾 Guarda tu sesión antes de salir",step4Sub:"Las categorías, presupuestos y recordatorios que crees solo existen en esta pestaña. Antes de cerrar, ve a Datos y pulsa Descargar .xlsx — la próxima vez sube ese archivo y Moneda recuperará todo.",
    gotIt:"¡Entendido — vamos! 🚀",
    spendingTitle:"Gasto por categoría",totalSpentIn:"Total gastado en",byMerchant:"Por comercio",
    insightsLabel:"Resumen",
    categoryGroups:"Grupos de categorías",createGroup:"+ Crear grupo (ej: Alimentación = Supermercado + Restaurantes)",
    newGroup:"Nuevo grupo",groupName:"Nombre del grupo (ej: Alimentación)",selectCategories:"Selecciona categorías:",
    createGroupBtn:"Crear grupo",removeGroup:"eliminar grupo",
    pickLang:"Elige tu idioma",
    welcomeTitle:"Bienvenido a Moneda",pickWorld:"Elige tu mundo",enterWorld:"Entrar en este mundo →",
    quickStart:"⚡ Inicio rápido — solo pon tu nombre",selected:"✓ Seleccionado",
    whatsYourName:"¿Cómo te llamas?",nameForDashboard:"Solo para tu panel — sin registro.",
    namePlaceholder:"Tu nombre…",letsGo:"¡Vamos! 🚀",continueBtn:"Continuar →",
    pickCompanion:"Elige tu acompañante",whoJoins:"¿Quién te acompaña en este viaje?",
    thisIsYou:"¡Este eres tú!",perfect:"¡Perfecto! →",
    whyHere:"¿Por qué estás aquí?",noWrongAnswers:"No hay respuestas incorrectas",
    startJourney:"¡A por ello! 🚀",pickOption:"Elige una opción arriba",
    customise:"Personalizar",customDone:"Hecho",
    dragReorder:"Arrastra los módulos para reordenar u oculta los que no necesitas:",
    visible:"Visible",hidden:"Oculto",
    wSummary:"📊 Resumen",wInsights:"💡 Estadísticas",wBudget:"🎯 Presupuesto",
    wPayments:"💳 Próximos cobros",wSpending:"📊 Gasto por categoría",
    wJournal:"📄 Movimientos",wIncome:"💰 Ingresos",
    wSubscriptions:"📦 Suscripciones y pagos fijos",
  }
};

// ── Category label translations ───────────────────────────────────────────────
export const CAT_LABELS = {
  en:{Groceries:"Groceries",Restaurants:"Restaurants",Transport:"Transport",Shopping:"Shopping",Subscriptions:"Subscriptions",Health:"Health",Housing:"Housing",Income:"Income","ATM / Cash":"ATM / Cash",Transfers:"Transfers",Entertainment:"Entertainment",Utilities:"Utilities",Education:"Education",Other:"Other"},
  es:{Groceries:"Supermercado",Restaurants:"Restaurantes",Transport:"Transporte",Shopping:"Compras",Subscriptions:"Suscripciones",Health:"Salud",Housing:"Vivienda",Income:"Ingresos","ATM / Cash":"Efectivo / Cajero",Transfers:"Transferencias",Entertainment:"Ocio",Utilities:"Suministros",Education:"Educación",Other:"Otros"}
};

// ── Spanish theme vocabulary ──────────────────────────────────────────────────
export const THEME_W_ES = {
  nature:    {home:"Mi Jardín",   txn:"Movimientos",   budget:"Límite del jardín",inc:"Cosecha", over:"Superaste el límite del jardín 🌱"},
  adventure: {home:"Sala del Mapa",txn:"Diario de viaje",budget:"Cofre de guerra",inc:"Botín",   over:"¡Cofre de guerra agotado! ⚔️"},
  princess:  {home:"Corte Real",  txn:"Libro de cuentas",budget:"Decreto Real",  inc:"Tributo", over:"¡Superando el decreto real! 👑"},
  finance:   {home:"Resumen",     txn:"Transacciones", budget:"Asignación",       inc:"Ingresos",over:"Presupuesto superado ⚠️"},
};

export const CC = {Groceries:"#4caf50",Restaurants:"#ff9800",Transport:"#2196f3",Shopping:"#e91e63",Subscriptions:"#9c27b0",Health:"#f44336",Housing:"#795548",Income:"#00bcd4","ATM / Cash":"#607d8b",Transfers:"#ff5722",Entertainment:"#3f51b5",Utilities:"#009688",Education:"#8bc34a",Other:"#9e9e9e"};
